version: '3.8'

# Services
services:
  # Server service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file: ./server/.env
    depends_on:
      - mongodb

  # Database service
  mongodb:
    image: mongo:latest
    container_name: mongodb_server
    ports:
      - "27017:27017"
    volumes:
      - ./../mydata:/data/db

# Volumes define
volumes: 
  mydata: